name: IPTV Otomatik Guncelle

on:
  workflow_dispatch: # El ile çalıştırmak için

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v3

      - name: Klasor Yapisini Goruntule
        run: ls -R # Hangi dosyaların nerede olduğunu siyah ekrana yazar

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri Yukle
        run: pip install requests beautifulsoup4 urllib3

      - name: Dosyaları Kaydet
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add deathless-selcuk.m3u DeaTHLesS-andro-panel.m3u || echo "Dosyalar bulunamadı"
          git commit -m "IPTV Listesi Guncellendi: $(date)" || echo "Degisiklik yok"
          git push origin master
