name: IPTV Otomatik Guncelle

on:
  workflow_dispatch: # El ile çalıştırmak için

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v3

      - name: Klasor Yapisini Goruntule
        run: ls -R # Hangi dosyaların nerede olduğunu siyah ekrana yazar

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri Yukle
        run: pip install requests beautifulsoup4 urllib3

      - name: Scriptleri Calistir
        run: |
          # Dosya isimlerini burada ls çıktısına göre teyit edeceğiz
          python deathless-selcuk.py || echo "Selcuk dosyasi bulunamadi"
          python deathless-andro-panel.py || echo "Andro dosyasi bulunamadi"
