- name: Scriptleri Calistir
        run: |
          ls -R # Mevcut dosyaları listeler (Hata tespiti için)
          python deathless-selcuk.py || echo "Selcuk scripti hata verdi"
          python deathless-andro-panel.py || echo "Andro scripti hata verdi"
